import json

from abinitio_sql_agent import agent as agent_module
from abinitio_sql_agent.agent import SQLUpdateAgent


def test_recommend_update_builds_guarded_sql(tmp_path):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
    failed_status: FAILED
    restart_status: READY_RETRY
    retry_count_column: retry_count
    last_error_column: last_error_message
    updated_at_column: updated_at
    notes: "orders"
""".strip()
    )

    agent = SQLUpdateAgent.from_yaml(schema)
    rec = agent.recommend_update(
        error_text="abinitio failed while loading orders",
        pk_column="order_id",
        pk_value="ORD-1",
    )

    assert "UPDATE stg_orders" in rec.sql
    assert "AND record_status = :failed_status" in rec.sql
    assert rec.params["restart_status"] == "READY_RETRY"
    assert rec.table == "stg_orders"


def test_recommend_update_with_llm_mode(tmp_path, monkeypatch):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
    failed_status: FAILED
    restart_status: READY_RETRY
""".strip()
    )

    class FakePrompt:
        @staticmethod
        def from_messages(_messages):
            return FakePrompt()

        def __or__(self, _other):
            return self

        def invoke(self, _payload):
            return json.dumps(
                {
                    "sql": "UPDATE stg_orders SET record_status = :restart_status WHERE order_id = :pk_value AND record_status = 'FAILED';",
                    "params": {"restart_status": "READY_RETRY"},
                    "explanation": "Generated by fake llm",
                }
            )

    class FakeChat:
        def __init__(self, *args, **kwargs):
            pass

        def __or__(self, _other):
            return self

    class FakeParser:
        def __ror__(self, other):
            return other

    monkeypatch.setattr(agent_module, "ChatPromptTemplate", FakePrompt)
    monkeypatch.setattr(agent_module, "ChatOpenAI", FakeChat)
    monkeypatch.setattr(agent_module, "StrOutputParser", FakeParser)

    agent = SQLUpdateAgent.from_yaml(schema, llm_model="fake-model")
    rec = agent.recommend_update(
        error_text="abinitio failed while loading orders",
        pk_column="order_id",
        pk_value="ORD-9",
    )

    assert "UPDATE stg_orders" in rec.sql
    assert rec.params["pk_value"] == "ORD-9"
    assert "Generated by fake llm" in rec.explanation
