import json

from abinitio_sql_agent import agent as agent_module
from abinitio_sql_agent.agent import SQLUpdateAgent


def test_recommend_update_builds_guarded_sql(tmp_path):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
    failed_status: FAILED
    restart_status: READY_RETRY
    retry_count_column: retry_count
    last_error_column: last_error_message
    updated_at_column: updated_at
    notes: "orders"
""".strip()
    )

    agent = SQLUpdateAgent.from_yaml(schema)
    rec = agent.recommend_update(
        log_data="abinitio failed while loading orders",
        pk_column="order_id",
        pk_value="ORD-1",
    )

    assert "UPDATE stg_orders" in rec.sql
    assert "AND record_status = :failed_status" in rec.sql
    assert rec.params["restart_status"] == "READY_RETRY"
    assert rec.table == "stg_orders"


def test_recommend_update_with_llm_mode(tmp_path, monkeypatch):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
    failed_status: FAILED
    restart_status: READY_RETRY
""".strip()
    )

    class FakePrompt:
        @staticmethod
        def from_messages(_messages):
            return FakePrompt()

        def __or__(self, _other):
            return self

        def invoke(self, payload):
            if "candidates_json" in payload:
                return json.dumps(
                    {
                        "table": "stg_orders",
                        "target_status": "READY_RETRY",
                        "reason": "orders context",
                    }
                )
            return json.dumps(
                {
                    "sql": "UPDATE stg_orders SET record_status = :restart_status WHERE order_id = :pk_value AND record_status = 'FAILED';",
                    "params": {"restart_status": "READY_RETRY"},
                    "explanation": "Generated by fake llm",
                }
            )

    class FakeChat:
        def __init__(self, *args, **kwargs):
            self.kwargs = kwargs

        def __or__(self, _other):
            return self

    class FakeParser:
        def __ror__(self, other):
            return other

    monkeypatch.setattr(agent_module, "ChatPromptTemplate", FakePrompt)
    monkeypatch.setattr(agent_module, "ChatOllama", FakeChat)
    monkeypatch.setattr(agent_module, "StrOutputParser", FakeParser)

    agent = SQLUpdateAgent.from_yaml(schema, llm_model="fake-model")
    rec = agent.recommend_update(
        log_data="abinitio failed while loading orders",
        pk_column="order_id",
        pk_value="ORD-9",
    )

    assert "UPDATE stg_orders" in rec.sql
    assert rec.params["pk_value"] == "ORD-9"
    assert rec.detected_status == "READY_RETRY"
    assert "Generated by fake llm" in rec.explanation


def test_llm_sql_accepts_nonstandard_placeholder_names(tmp_path, monkeypatch):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
    failed_status: FAILED
    restart_status: READY_RETRY
""".strip()
    )

    class FakePrompt:
        @staticmethod
        def from_messages(_messages):
            return FakePrompt()

        def __or__(self, _other):
            return self

        def invoke(self, payload):
            if "candidates_json" in payload:
                return json.dumps(
                    {
                        "table": "stg_orders",
                        "target_status": "READY_RETRY",
                        "reason": "orders context",
                    }
                )
            return json.dumps(
                {
                    "sql": (
                        "UPDATE stg_orders SET record_status = :new_status "
                        "WHERE order_id = :id_value AND record_status = :current_status;"
                    ),
                    "params": {
                        "new_status": "READY_RETRY",
                        "id_value": "ORD-1001",
                        "current_status": "FAILED",
                    },
                    "explanation": "Generated by fake llm",
                }
            )

    class FakeChat:
        def __init__(self, *args, **kwargs):
            self.kwargs = kwargs

        def __or__(self, _other):
            return self

    class FakeParser:
        def __ror__(self, other):
            return other

    monkeypatch.setattr(agent_module, "ChatPromptTemplate", FakePrompt)
    monkeypatch.setattr(agent_module, "ChatOllama", FakeChat)
    monkeypatch.setattr(agent_module, "StrOutputParser", FakeParser)

    agent = SQLUpdateAgent.from_yaml(schema, llm_model="fake-model")
    rec = agent.recommend_update(
        log_data="abinitio failed while loading orders",
        pk_column="order_id",
        pk_value="ORD-1001",
    )

    assert ":id_value" in rec.sql
    assert ":current_status" in rec.sql
    assert "fallback template" not in rec.explanation.lower()


def test_llm_sql_without_where_clause_is_accepted(tmp_path, monkeypatch):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
    failed_status: FAILED
    restart_status: READY_RETRY
""".strip()
    )

    class FakePrompt:
        @staticmethod
        def from_messages(_messages):
            return FakePrompt()

        def __or__(self, _other):
            return self

        def invoke(self, payload):
            if "candidates_json" in payload:
                return json.dumps(
                    {
                        "table": "stg_orders",
                        "target_status": "READY_RETRY",
                        "reason": "orders context",
                    }
                )
            return json.dumps(
                {
                    "sql": "UPDATE stg_orders SET record_status = :restart_status;",
                    "params": {"restart_status": "READY_RETRY"},
                    "explanation": "Generated by fake llm",
                }
            )

    class FakeChat:
        def __init__(self, *args, **kwargs):
            self.kwargs = kwargs

        def __or__(self, _other):
            return self

    class FakeParser:
        def __ror__(self, other):
            return other

    monkeypatch.setattr(agent_module, "ChatPromptTemplate", FakePrompt)
    monkeypatch.setattr(agent_module, "ChatOllama", FakeChat)
    monkeypatch.setattr(agent_module, "StrOutputParser", FakeParser)

    agent = SQLUpdateAgent.from_yaml(schema, llm_model="fake-model")
    rec = agent.recommend_update(
        log_data="abinitio failed while loading orders",
        pk_column="order_id",
        pk_value="ORD-2002",
    )

    assert rec.sql.strip() == "UPDATE stg_orders SET record_status = :restart_status;"
    assert "fallback template" not in rec.explanation.lower()


def test_selector_can_choose_table_and_status_from_rag_candidates(tmp_path, monkeypatch):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
    failed_status: FAILED
    restart_status: READY_RETRY
    notes: "orders pipeline"
  - table: stg_customers
    primary_keys: [customer_id]
    status_column: status_flag
    failed_status: E
    restart_status: N
    notes: "customer reconciliation"
""".strip()
    )

    class FakePrompt:
        @staticmethod
        def from_messages(_messages):
            return FakePrompt()

        def __or__(self, _other):
            return self

        def invoke(self, payload):
            if "candidates_json" in payload:
                return json.dumps(
                    {
                        "table": "stg_customers",
                        "target_status": "N",
                        "reason": "customer terms detected in log",
                    }
                )
            return json.dumps(
                {
                    "sql": "UPDATE stg_customers SET status_flag = :restart_status WHERE customer_id = :pk_value AND status_flag = :failed_status;",
                    "params": {"restart_status": "N", "failed_status": "E"},
                    "explanation": "Generated by fake llm",
                }
            )

    class FakeChat:
        def __init__(self, *args, **kwargs):
            self.kwargs = kwargs

        def __or__(self, _other):
            return self

    class FakeParser:
        def __ror__(self, other):
            return other

    monkeypatch.setattr(agent_module, "ChatPromptTemplate", FakePrompt)
    monkeypatch.setattr(agent_module, "ChatOllama", FakeChat)
    monkeypatch.setattr(agent_module, "StrOutputParser", FakeParser)

    agent = SQLUpdateAgent.from_yaml(schema, llm_model="fake-model")
    rec = agent.recommend_update(
        log_data="abinitio customer reconciliation failed with duplicate customer_id",
        pk_column="customer_id",
        pk_value="C-99",
    )

    assert rec.table == "stg_customers"
    assert rec.detected_status == "N"


def test_recommend_update_can_infer_pk_from_schema_and_log(tmp_path):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
    failed_status: FAILED
    restart_status: READY_RETRY
""".strip()
    )

    agent = SQLUpdateAgent.from_yaml(schema)
    rec = agent.recommend_update(
        log_data="abinitio failed while loading orders with order_id=ORD-77",
    )

    assert "WHERE order_id = :pk_value" in rec.sql
    assert rec.params["pk_value"] == "ORD-77"


def test_recommend_update_raises_if_pk_value_not_provided_or_in_log(tmp_path):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
""".strip()
    )

    agent = SQLUpdateAgent.from_yaml(schema)

    try:
        agent.recommend_update(log_data="abinitio failed while loading orders")
    except ValueError as exc:
        assert "Could not infer primary key value" in str(exc)
    else:  # pragma: no cover - assertion path
        raise AssertionError("Expected recommend_update to raise ValueError")


def test_recommend_update_can_extract_pk_from_failed_record_block(tmp_path):
    schema = tmp_path / "schema.yaml"
    schema.write_text(
        """
tables:
  - table: stg_orders
    primary_keys: [order_id]
    status_column: record_status
    failed_status: FAILED
    restart_status: READY_RETRY
""".strip()
    )

    agent = SQLUpdateAgent.from_yaml(schema)
    rec = agent.recommend_update(
        log_data=(
            "[17:05:44] ERROR : DB Execute Component (mp_load_stg_orders)\n"
            "Failed Record:\n"
            "order_id=ORD102938|customer_id=CUST8891|amount=2500|status=NEW\n"
        ),
    )

    assert rec.params["pk_value"] == "ORD102938"


def test_from_log_can_infer_schema_and_generate_sql():
    log_data = (
        "Ab Initio Graph Execution Log\n"
        "[17:05:43] INFO  : Loading records into table STG_ORDERS\n"
        "[17:05:44] ERROR : DB Execute Component (mp_load_stg_orders)\n"
        "Failed Record:\n"
        "order_id=ORD102938|customer_id=CUST8891|amount=2500|status=NEW\n"
    )

    agent = SQLUpdateAgent.from_log(log_data)
    rec = agent.recommend_update(log_data=log_data)

    assert rec.table.lower() == "stg_orders"
    assert "WHERE order_id = :pk_value" in rec.sql
    assert rec.params["pk_value"] == "ORD102938"


def test_from_log_handles_escaped_newlines_when_inferring_schema():
    log_data = (
        "[17:05:43] INFO  : Loading records into table STG_ORDERS\n"
        "[17:05:44] ERROR : DB Execute Component (mp_load_stg_orders)\n"
        "Failed Record:\n"
        "order_id=ORD777|customer_id=CUST1|amount=50|status=NEW\n"
    )

    agent = SQLUpdateAgent.from_log(log_data)
    rec = agent.recommend_update(log_data=log_data)

    assert rec.table.lower() == "stg_orders"
    assert rec.params["pk_value"] == "ORD777"
